### ISSUE TITLE
Notas Gerais Ficha 3

### ISSUE THREAD

**Issue by davidrobert99** [JuanFernandes99/Laboratorio_de_programacao#2]
O código parece-me bem. Só um pequeno detalhe, na finção ``` getConta()``` não era necessario ```fazer o toLowerCase()``` nas duas Strings.

```java
if (contaBancaria.getTitular().toLowerCase().equals(aNome.toLowerCase())) { // para comparar strings é
```

**Comment by JuanFernandes99** [comment]
Obrigado :) , já corrigirei.
